source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:Real-young/Real_FMSpecs.git'

use_frameworks!

target 'Real_FMMain_Example' do
  pod 'Real_FMMain', :path => '../'

  target 'Real_FMMain_Tests' do
    inherit! :search_paths

    
  end
end
